Feat/issue 2
Endless-Creation-32nd/hipSpot-toyproject-frontend pull request #3
Opened 2022-10-16 16:44 UTC by yeoularu

## Motivation

- msw.js를 사용하여 모킹 API와 데이터를 만들고 사용했습니다.
- 리액트 훅, 리코일 atom/selector를 사용하여 데이터 흐름 함수들을 모듈화 했습니다.

<br>

## Key Changes

- src/ apis, hooks, mocks, recoil 폴더가 생성되었습니다.
- src/index.js가 변경되었습니다. (React.Suspense)

### 스크린샷

src 폴더 스크린샷

- ![src 폴더 스크린샷](https://github.com/Endless-Creation-32nd/hipSpot-toyproject-frontend/blob/feat/issue-2/.github/src.png?raw=true)

index.js 스크린샷

- ![index.js 스크린샷](https://github.com/Endless-Creation-32nd/hipSpot-toyproject-frontend/blob/feat/issue-2/.github/index.js.png?raw=true)

<br>

## To Reviewers

- JS, React 로직 오류나 잘못된 코딩 습관(변수명 등)을 중점으로 보면서 검토해주세요
- 깃 커밋메세지 등 커뮤니케이션에 문제가 있는지 알려주세요

2022-10-17 06:20 UTC, sjsjsj1246 requested changes
일단 전체적인 구조만 파악을 해봤구요 나머지 로직은 추후 다시 살펴보겠습니다.
일단 현재 제안사항 반영 부탁드려요

2022-10-17 06:20 UTC, sjsjsj1246 commented on src/index.js
>    <React.StrictMode>
<React.StrictMode>도 제거해줍시다

2022-10-17 06:20 UTC, sjsjsj1246 commented on src/mocks/todo/service.js
> +  if (!target) return;
```suggestion
  if (!target) return res(ctx.status(404));
```

이렇게 에러 코드를 전달해주는 게 좋을 것 같습니다.

2022-10-17 06:20 UTC, sjsjsj1246 commented on src/mocks/todo/service.js
> +  if (!target) return;
```suggestion
  if (!target) return res(ctx.status(404));
```

2022-10-17 06:20 UTC, sjsjsj1246 commented on src/mocks/todo/service.js
> +  if (targetIndex === -1) return;
```suggestion
  if (targetIndex === -1) return res(ctx.status(404));
```

2022-10-17 07:12 UTC, yeoularu commented on .github/ISSUE_TEMPLATE/feature.md
> +- React, Recoil 공식문서를 참고하여 개발합니다.
제안사항 반영 코드 수정 후 git push 했습니다.

2022-10-17 07:18 UTC, Sangjun-man approved these changes
전체적으로 문제 없는것 같아요 잘하셨네용 깃헙 이슈탬플릿 파일만 돌려놓으면 될것같아요 고생하셨어요~~~

2022-10-18 05:31 UTC, sjsjsj1246 approved these changes
나머지 로직 잘 확인 했습니다. 수고하셨습니다

2022-10-18 09:28 UTC, sjsjsj1246 commented
@yeoularu 머지 하시면 돼요!

2022-10-18 09:34 UTC, merged